prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/app_29925_logo_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/clienti_nume.sql
@@application/shared_components/user_interface/lovs/lista_medici.sql
@@application/shared_components/user_interface/lovs/medici_nume.sql
@@application/shared_components/user_interface/lovs/specialitate_nume_specialitate.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00012.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_09999.sql
@@application/end_environment.sql
