CREATE TABLE "ACORDURI" 
   (	"ID_ACORD" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NUME_ACORD" VARCHAR2(25) NOT NULL ENABLE, 
	"ID_CLIENT" NUMBER NOT NULL ENABLE, 
	"RASPUNS" VARCHAR2(2) NOT NULL ENABLE, 
	 CHECK (raspuns IN ('DA', 'NU')) ENABLE, 
	 PRIMARY KEY ("ID_ACORD")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ASOCIERE_CLIENTI_MEDICI" 
   (	"ID_CLIENT" NUMBER NOT NULL ENABLE, 
	"ID_MEDIC" NUMBER NOT NULL ENABLE
   ) ;

  CREATE TABLE "CHELTUIELI_DIVERSE" 
   (	"ID_CHELTUIALA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NUME_CHELTUIALA" VARCHAR2(25) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_CHELTUIALA")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CLIENTI" 
   (	"ID_CLIENT" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NUME" VARCHAR2(25) NOT NULL ENABLE, 
	"PRENUME" VARCHAR2(25) NOT NULL ENABLE, 
	"TELEFON" NUMBER(10,0) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(50), 
	"DATA_NASTERII" DATE, 
	"ID_SURSA" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_CLIENT")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CONSUMABILE_PER_SERVICIU" 
   (	"ID_SERVICIU" NUMBER NOT NULL ENABLE, 
	"ID_PRODUS" NUMBER NOT NULL ENABLE, 
	"CANTITATE_NECESARA" NUMBER NOT NULL ENABLE
   ) ;

  CREATE TABLE "ESTIMARE_DURATA_SERVICII" 
   (	"ID_DURATA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TIMP_ESTIMATIV_MIN" NUMBER NOT NULL ENABLE, 
	"ID_SERVICIU" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_DURATA")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "MEDICI" 
   (	"ID_MEDIC" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NUME" VARCHAR2(25) NOT NULL ENABLE, 
	"PRENUME" VARCHAR2(25) NOT NULL ENABLE, 
	"ID_SPECIALITATE" NUMBER NOT NULL ENABLE, 
	"TELEFON" NUMBER(10,0) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(50) NOT NULL ENABLE, 
	"DATA_ANGAJARII" DATE NOT NULL ENABLE, 
	"SALAR" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_MEDIC")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PLATI_CHELTUIELI_DIVERSE" 
   (	"ID_PLATA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_CHELTUIALA" NUMBER NOT NULL ENABLE, 
	"COST" NUMBER(7,2) NOT NULL ENABLE, 
	"DATA" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_PLATA")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PROGRAMARI" 
   (	"ID_PROGRAMARE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_CLIENT" NUMBER NOT NULL ENABLE, 
	"ID_MEDIC" NUMBER NOT NULL ENABLE, 
	"DATA_PROGRAMARE" DATE, 
	"ID_SERVICIU" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_PROGRAMARE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "RECENZII" 
   (	"ID_RECENZIE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"RECENZIE" NUMBER NOT NULL ENABLE, 
	"ID_CLIENT" NUMBER NOT NULL ENABLE, 
	"ID_MEDIC" NUMBER NOT NULL ENABLE, 
	"ID_PROGRAMARE" NUMBER NOT NULL ENABLE, 
	 CHECK (recenzie IN (1, 2, 3, 4, 5)) ENABLE, 
	 PRIMARY KEY ("ID_RECENZIE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SERVICII" 
   (	"ID_SERVICIU" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NUME_SERVICU" VARCHAR2(50) NOT NULL ENABLE, 
	"PRET" NUMBER(7,2) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_SERVICIU")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SPECIALITATE" 
   (	"ID_SPECIALITATE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NUME_SPECIALITATE" VARCHAR2(25) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_SPECIALITATE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "STOC_CONSUMABILE" 
   (	"ID_PRODUS" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NUME_PRODUS" VARCHAR2(50) NOT NULL ENABLE, 
	"CANTITATE" NUMBER NOT NULL ENABLE, 
	"PRET_UNITAR" NUMBER(7,2), 
	 PRIMARY KEY ("ID_PRODUS")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SURSA_RECOMANDARE" 
   (	"ID_SURSA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NUME_SURSA" VARCHAR2(50) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_SURSA")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "ACORDURI" ADD FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "CLIENTI" ("ID_CLIENT") ENABLE;

  ALTER TABLE "ASOCIERE_CLIENTI_MEDICI" ADD FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "CLIENTI" ("ID_CLIENT") ENABLE;
  ALTER TABLE "ASOCIERE_CLIENTI_MEDICI" ADD FOREIGN KEY ("ID_MEDIC")
	  REFERENCES "MEDICI" ("ID_MEDIC") ENABLE;

  ALTER TABLE "CONSUMABILE_PER_SERVICIU" ADD FOREIGN KEY ("ID_SERVICIU")
	  REFERENCES "SERVICII" ("ID_SERVICIU") ENABLE;
  ALTER TABLE "CONSUMABILE_PER_SERVICIU" ADD FOREIGN KEY ("ID_PRODUS")
	  REFERENCES "STOC_CONSUMABILE" ("ID_PRODUS") ENABLE;

  ALTER TABLE "ESTIMARE_DURATA_SERVICII" ADD FOREIGN KEY ("ID_SERVICIU")
	  REFERENCES "SERVICII" ("ID_SERVICIU") ENABLE;

  ALTER TABLE "MEDICI" ADD FOREIGN KEY ("ID_SPECIALITATE")
	  REFERENCES "SPECIALITATE" ("ID_SPECIALITATE") ENABLE;

  ALTER TABLE "PLATI_CHELTUIELI_DIVERSE" ADD FOREIGN KEY ("ID_CHELTUIALA")
	  REFERENCES "CHELTUIELI_DIVERSE" ("ID_CHELTUIALA") ENABLE;

  ALTER TABLE "PROGRAMARI" ADD FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "CLIENTI" ("ID_CLIENT") ENABLE;
  ALTER TABLE "PROGRAMARI" ADD FOREIGN KEY ("ID_MEDIC")
	  REFERENCES "MEDICI" ("ID_MEDIC") ENABLE;
  ALTER TABLE "PROGRAMARI" ADD FOREIGN KEY ("ID_SERVICIU")
	  REFERENCES "SERVICII" ("ID_SERVICIU") ENABLE;

  ALTER TABLE "RECENZII" ADD FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "CLIENTI" ("ID_CLIENT") ENABLE;
  ALTER TABLE "RECENZII" ADD FOREIGN KEY ("ID_MEDIC")
	  REFERENCES "MEDICI" ("ID_MEDIC") ENABLE;
  ALTER TABLE "RECENZII" ADD FOREIGN KEY ("ID_PROGRAMARE")
	  REFERENCES "PROGRAMARI" ("ID_PROGRAMARE") ENABLE;


  CREATE UNIQUE INDEX "SYS_C00172494263" ON "SPECIALITATE" ("ID_SPECIALITATE") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494272" ON "STOC_CONSUMABILE" ("ID_PRODUS") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494281" ON "SERVICII" ("ID_SERVICIU") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494286" ON "CHELTUIELI_DIVERSE" ("ID_CHELTUIALA") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494295" ON "ESTIMARE_DURATA_SERVICII" ("ID_DURATA") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494312" ON "MEDICI" ("ID_MEDIC") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494319" ON "CLIENTI" ("ID_CLIENT") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494335" ON "ACORDURI" ("ID_ACORD") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172497257" ON "SURSA_RECOMANDARE" ("ID_SURSA") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172498154" ON "PLATI_CHELTUIELI_DIVERSE" ("ID_PLATA") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172500747" ON "PROGRAMARI" ("ID_PROGRAMARE") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172501152" ON "RECENZII" ("ID_RECENZIE") 
  ;


create or replace procedure AD_ANGJAT 
(
  NUMEANG IN VARCHAR2,
  PRENUMEANG IN VARCHAR2,
  EMAIL IN VARCHAR2,
  TEL IN VARCHAR2
)
as 
begin
  INSERT INTO ANGAJATI (ID_ANGAJAT, NUME, PRENUME, E_MAIL, TELEFON) 
  values (null, NUMEANG, PRENUMEANG, EMAIL, TEL);
end AD_ANGJAT;
/


Rem No sequence found to generate DDL.

Rem No synonym found to generate DDL.


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_MEDICI_CU_SPECIALITATE" ("NUME", "PRENUME", "SPECIALITATE", "TELEFON", "EMAIL", "Data Angajarii", "SALAR") AS 
  SELECT
    nume,
    prenume,
    nume_specialitate AS specialitate,
    telefon,
    email,
    data_angajarii as "Data Angajarii",
    salar
FROM medici
JOIN specialitate ON specialitate.id_specialitate = medici.id_specialitate;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_NUMAR_CLIENTI_PER_MEDIC" ("Medic", "Numar clienti") AS 
  SELECT
    medici.nume || ' ' || medici.prenume AS "Medic",
    COUNT(asociere_clienti_medici.id_client) AS "Numar clienti"
FROM medici
JOIN asociere_clienti_medici ON asociere_clienti_medici.id_medic = medici.id_medic
JOIN clienti ON asociere_clienti_medici.id_client = clienti.id_client
GROUP BY medici.id_medic, medici.nume, medici.prenume
ORDER BY COUNT(asociere_clienti_medici.id_client) DESC;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_RECENZIE_MEDIE_MEDIC" ("Nume Medic", "Recenzie Medie") AS 
  SELECT 
    nume || ' ' || prenume AS "Nume Medic",
    ROUND(AVG(recenzie), 2) AS "Recenzie Medie"
FROM recenzii
JOIN medici ON medici.id_medic = recenzii.id_medic
GROUP BY recenzii.id_medic, nume, prenume;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_SITUATIE_RECENZII" ("RECENZIE", "Numar Recenzii") AS 
  SELECT 
    recenzie, 
    COUNT(recenzie) AS "Numar Recenzii"
FROM recenzii
GROUP BY recenzie
ORDER BY recenzie;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_TOTAL_PROGRAMARI_PE_LUNA" ("Luna si Anul", "Total Programari") AS 
  SELECT
    TO_CHAR(data_programare, 'MM') || '/' || TO_CHAR(data_programare, 'YYYY') AS "Luna si Anul",
    COUNT(*) AS "Total Programari"
FROM programari
GROUP BY TO_CHAR(data_programare, 'MM'), TO_CHAR(data_programare, 'YYYY')
ORDER BY TO_CHAR(data_programare, 'YYYY'), TO_CHAR(data_programare, 'MM');
Rem No database link found to generate DDL.


  CREATE UNIQUE INDEX "SYS_C00172494335" ON "ACORDURI" ("ID_ACORD") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494286" ON "CHELTUIELI_DIVERSE" ("ID_CHELTUIALA") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494319" ON "CLIENTI" ("ID_CLIENT") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494295" ON "ESTIMARE_DURATA_SERVICII" ("ID_DURATA") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494312" ON "MEDICI" ("ID_MEDIC") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172498154" ON "PLATI_CHELTUIELI_DIVERSE" ("ID_PLATA") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172500747" ON "PROGRAMARI" ("ID_PROGRAMARE") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172501152" ON "RECENZII" ("ID_RECENZIE") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494281" ON "SERVICII" ("ID_SERVICIU") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494263" ON "SPECIALITATE" ("ID_SPECIALITATE") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172494272" ON "STOC_CONSUMABILE" ("ID_PRODUS") 
  ;

  CREATE UNIQUE INDEX "SYS_C00172497257" ON "SURSA_RECOMANDARE" ("ID_SURSA") 
